name = "lunch-menu-scraper"
main = "src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = [
  "*/10 0-2 * * 1-5"  # 매일 평일 한국시간 오전 9시~11시 (UTC 0시~2시), 10분마다 실행
]
